t_test=function(alfa,n,sample_mean,pop_mean,sigma)
{
  sample_mean=mean(x)
  s=sd(x)
  critical_t=qt(1-alfa,n-1)
  t_score=(sample_mean-pop_mean)/(s/sqrt(n))
  print(critical_t)
  print(t_score)
}
t_test(0.01,100,11.9,11.4,0.25)