t_test=function(alfa,n,sample_mean,pop_mean,sigma)
{
  s=sqrt(sigma)
  critical_t=qt(1-alfa,n-1)
  t_score=(sample_mean-pop_mean)/(s/sqrt(n))
  print(critical_t)
  print(t_score)
}
t_test(0.05,40,29,30,5)